#!/usr/bin/env python3
"""Generate neural TTS audio for a language's course content.

Reads the spoken-string list from tools/dump-strings.js, synthesizes each with
Microsoft Edge neural voices (edge-tts), and writes content-addressed MP3s plus
a text->file manifest into site/<code>/audio/.

Idempotent: existing files are kept, orphans are deleted, the manifest is
rewritten every run.

Usage:
  pip3 install edge-tts
  python3 tools/gen-audio.py fr [--limit N]
"""
import asyncio
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

import edge_tts

VOICES = {
    "fr": "fr-FR-DeniseNeural",
    "de": "de-DE-KatjaNeural",
    "ru": "ru-RU-SvetlanaNeural",
    "it": "it-IT-ElsaNeural",
    "es": "es-MX-DaliaNeural",
}
RATE = "-5%"          # slightly slower for learners (matches the app's 0.95 TTS rate)
CONCURRENCY = 8
RETRIES = 3

SITE = Path(__file__).resolve().parent.parent


def speech_text(text: str) -> str:
    """Preprocess for synthesis only — manifest keys keep the exact original."""
    return re.sub(r"\s*/\s*", ", ", text)


def fname(text: str) -> str:
    return hashlib.sha1(text.encode("utf-8")).hexdigest()[:16] + ".mp3"


async def synth(sem: asyncio.Semaphore, voice: str, text: str, dest: Path) -> bool:
    async with sem:
        for attempt in range(RETRIES):
            try:
                tmp = dest.with_suffix(".tmp")
                await edge_tts.Communicate(speech_text(text), voice, rate=RATE).save(str(tmp))
                if tmp.stat().st_size < 200:  # sanity: an mp3 this small is broken
                    tmp.unlink()
                    raise RuntimeError("suspiciously small output")
                tmp.rename(dest)
                return True
            except Exception as e:
                if attempt == RETRIES - 1:
                    print(f"FAILED: {text[:60]!r}: {e}", file=sys.stderr)
                    return False
                await asyncio.sleep(2 * (attempt + 1))
    return False


async def main() -> None:
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    if not args or args[0] not in VOICES:
        sys.exit(f"usage: gen-audio.py <{'|'.join(VOICES)}> [--limit N]")
    code = args[0]
    limit = None
    for a in sys.argv[1:]:
        if a.startswith("--limit"):
            limit = int(sys.argv[sys.argv.index(a) + 1] if a == "--limit" else a.split("=")[1])

    out = subprocess.run(
        ["node", str(SITE / "tools" / "dump-strings.js"), code],
        capture_output=True, text=True, check=True,
    )
    texts = json.loads(out.stdout)
    if limit:
        texts = texts[:limit]
    print(f"{code}: {len(texts)} strings, voice {VOICES[code]}")

    audio_dir = SITE / code / "audio"
    audio_dir.mkdir(parents=True, exist_ok=True)

    manifest = {t: fname(t) for t in texts}
    if len(set(manifest.values())) != len(manifest):
        sys.exit("sha1 filename collision — investigate before generating")

    todo = [(t, audio_dir / f) for t, f in manifest.items() if not (audio_dir / f).exists()]
    print(f"{len(manifest) - len(todo)} cached, {len(todo)} to synthesize")

    sem = asyncio.Semaphore(CONCURRENCY)
    done = 0
    failed = 0

    async def run(t, dest):
        nonlocal done, failed
        ok = await synth(sem, VOICES[code], t, dest)
        done += 1
        failed += 0 if ok else 1
        if done % 100 == 0 or done == len(todo):
            print(f"  {done}/{len(todo)} ({failed} failed)")

    await asyncio.gather(*(run(t, dest) for t, dest in todo))

    if failed:
        sys.exit(f"{failed} strings failed — rerun to retry (existing files are kept)")

    # drop orphans from previous content versions (only when generating the full set)
    if not limit:
        keep = set(manifest.values()) | {"manifest.js"}
        for f in audio_dir.iterdir():
            if f.name not in keep:
                f.unlink()

        (audio_dir / "manifest.js").write_text(
            "/* GENERATED by tools/gen-audio.py — do not edit. */\n"
            "window.AUDIO_FILES = " + json.dumps(manifest, ensure_ascii=False) + ";\n",
            encoding="utf-8",
        )
        print("wrote manifest.js")

    size = sum(f.stat().st_size for f in audio_dir.glob("*.mp3"))
    print(f"total: {len(list(audio_dir.glob('*.mp3')))} files, {size // 1024 // 1024} MB")


if __name__ == "__main__":
    asyncio.run(main())
