#!/usr/bin/env node
/* Sync course content from the per-language repos into the site.
   - Copies <Lang>/output/data → site/<code>/data for the 5 merged languages.
   - Copies English/output → site/english (the standalone English app).
   - Regenerates site/manifest.js listing each language's data files in load order.
   Run from anywhere: node tools/sync.js */

const fs = require("fs");
const path = require("path");

const SITE = path.resolve(__dirname, "..");
const ROOT = path.resolve(SITE, "..");

const LANGS = {
  fr: "French",
  de: "German",
  ru: "Russian",
  it: "Italian",
  es: "Spanish",
};

function rimraf(p) {
  fs.rmSync(p, { recursive: true, force: true });
}

function copyDir(src, dest) {
  fs.mkdirSync(dest, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    if (entry.name === ".DS_Store") continue;
    const s = path.join(src, entry.name);
    const d = path.join(dest, entry.name);
    if (entry.isDirectory()) copyDir(s, d);
    else fs.copyFileSync(s, d);
  }
}

function dirSize(p) {
  let n = 0;
  for (const entry of fs.readdirSync(p, { withFileTypes: true })) {
    const f = path.join(p, entry.name);
    n += entry.isDirectory() ? dirSize(f) : fs.statSync(f).size;
  }
  return n;
}

const manifest = {};

for (const [code, folder] of Object.entries(LANGS)) {
  const src = path.join(ROOT, folder, "output", "data");
  if (!fs.existsSync(src)) {
    console.error(`FATAL: missing source dir ${src}`);
    process.exit(1);
  }
  const dest = path.join(SITE, code, "data");
  rimraf(dest);
  copyDir(src, dest);

  const files = fs.readdirSync(dest).filter((f) => f.endsWith(".js")).sort();
  if (!files.includes("course.js")) {
    console.error(`FATAL: ${folder} data has no course.js`);
    process.exit(1);
  }
  // course.js must load first; lesson files follow in sorted order.
  manifest[code] = ["course.js", ...files.filter((f) => f !== "course.js")];
  const kb = Math.round(dirSize(dest) / 1024);
  console.log(`${code}  ${folder.padEnd(8)} ${String(files.length).padStart(3)} files  ${kb} KB`);
}

const engSrc = path.join(ROOT, "English", "output");
if (!fs.existsSync(engSrc)) {
  console.error(`FATAL: missing ${engSrc}`);
  process.exit(1);
}
const engDest = path.join(SITE, "english");
rimraf(engDest);
copyDir(engSrc, engDest);
console.log(`en  English  ${Math.round(dirSize(engDest) / 1024)} KB (full app)`);

fs.writeFileSync(
  path.join(SITE, "manifest.js"),
  "/* GENERATED by tools/sync.js — do not edit. */\n" +
    "window.SITE_MANIFEST = " + JSON.stringify(manifest, null, 2) + ";\n"
);
console.log("Wrote manifest.js");
